version: 0.2

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_REPOSITORY=docker-cicd-demo
      - AWS_REGION=$AWS_DEFAULT_REGION
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t $ECR_REPOSITORY .
      - docker tag $ECR_REPOSITORY:latest $ECR_URI:latest

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR
      - docker push $ECR_URI:latest
      - echo Docker image pushed successfully
